### ISSUE TITLE
Unable to edit form. Cursor moves to end on any event in the input box.

### ISSUE THREAD

**Issue by sai7** [hamzahamidi/Angular6-json-schema-form#45]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
**A clear and concise description of what the bug is.**
In an Angular 6 application, after successfully creating the form, when trying to edit or delete the text from input text or text area, the cursor constantly moves to the end of each interaction.

**To Reproduce**

1. Create an Angular app.
2. Include Angular6-json-schema-form library as documented.
3. Define schema and create the layout according to the flex layout.
4. Enter some text into the input box or text area, the described problem occurs.

**Expected behavior**
We should be able to enter or edit text in the text-box even from the middle of the text.  

**Screenshots**
Please refer to the following youtube video: [https://youtu.be/fp5UYvRzZLY](https://youtu.be/fp5UYvRzZLY)

**Desktop (please complete the following information):**

- OS: Windows, MacOS and Linux
- Browser: Chrome, Safari, Firefox, IE
- Version: latest

**Log output covering before the error and any error statements**

NA

**Additional context**
I am not sure, whether this problem is caused by the new layout I have used or any misconfiguration. Let me know if any working prototype is needed. 

**Context**

Editing of the forms is a compulsory task for all the users.

Editing of the forms is a compulsory task for all the users.

**Comment by RS-Roshi** [comment]
Try to change the framework to bootstrap just to test it whether it happens in bootstrap also or not...

**Comment by sai7** [comment]
Resolved this problem by referring to another issue [here](https://github.com/hamzahamidi/Angular6-json-schema-form/issues/25#issuecomment-442831746)

**Comment by ishaan-puniani** [comment]
Hello @sai7 , 
The issue still exists. 
as per the solution, provided in https://github.com/hamzahamidi/Angular6-json-schema-form/issues/25

ngModel doesn't seem to be supporting two data binding, so, ngModel does not work for me as I need to show repopulated data in the which is not working with [(ngModel)] however works fine with [(data)] binding.

**Comment by ChristosAsvestopoulos** [comment]
@ishaan-puniani did you find a workaround that supports **two way binding** and **solves this issue with the cursor**?
It seems to me that we have the following options:

- [(ngModel)] -> solves cursor issue, no two-way-binding
- [(data)] -> cursor issue, two-way-binding
